---
output: github_document
---

#networkGen Package

This package is used to generate network mazes. Currently it is at the version 0.1.0.

The functions will help you to generate trail or circuit type mazes. 

In some of the mazes, unidirectional arrows can be included (Up to 3 arrows). 

Please bear in mind that when it comes to 3 arrows in a maze, the item may not be solvable. Hence, it will be a good idea to set.seed so that you know which maze is cannot be completed successfully. I may introduce some type of algorithm such that the geneated maze with 3 arrows will always be solvable. But that is for further work. 



More to come soon! 

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

---

R/networkGen is an [R](https://www.r-project.org) package with R functions that are
useful to me for automatically generating network mazes for research. These are the most important functions in the package.

- networkGen
    - `netHTML`
    - `netHTML1arrow`
    - `netHTML2arrows`
    - `netHTML3arrows`

---



License

This package is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License, version 3, as published by the Free Software Foundation.

This program is distributed in the hope that it will be useful, but without any warranty; without even the implied warranty of merchantability or fitness for a particular purpose. See the GNU General Public License for more details.

A copy of the GNU General Public License, version 3, is available at https://www.r-project.org/Licenses/GPL-3